export type ShipMountDepositSymbol =
  | "QUARTZ_SAND"
  | "SILICON_CRYSTALS"
  | "PRECIOUS_STONES"
  | "ICE_WATER"
  | "AMMONIA_ICE"
  | "IRON_ORE"
  | "COPPER_ORE"
  | "SILVER_ORE"
  | "ALUMINUM_ORE"
  | "GOLD_ORE"
  | "PLATINUM_ORE"
  | "DIAMONDS"
  | "URANITE_ORE"
  | "MERITIUM_ORE";
